### ISSUE TITLE
data-preprocessing_and_base-model_training.py 

### ISSUE THREAD

**Issue by aravhanshik** [SusmitSekharBhakta/Stock-market-price-prediction#1]
final_data.csv file is not present. 
Line 22 dataFrame = pd.read_csv('/content/final_data.csv', index_col=0)

**Comment by SusmitSekharBhakta** [comment]
Thank you telling. However, you don't need that file yet. Please see the updated version.

**Comment by aravhanshik** [comment]
Hi I am interested in learning about the project and its working.
How can I contact you?
Also I am unable to execute the project
